version: '3'

services:
  ai-module-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./extracted_data:/app/extracted_data
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1